-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- Auto remove unused imports on file save typescript and javascript only.
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   group = vim.api.nvim_create_augroup("TS_RemoveUnusedImports", { clear = true }),
--   desc = "TS_RemoveUnusedImports",
--   pattern = { "*.ts", "*.tsx", "*.js", "*.jsx" },
--   callback = function()
--     vim.cmd([[TSToolsRemoveUnusedImports]])
--     vim.cmd("write")
--   end,
-- })

-- Testing Typescript GO v7.0.0-dev as LSP
-- local function start_tsgo()
--   local root_files = { "tsconfig.json", "jsconfig.json", "package.json", ".git" }
--   local paths = vim.fs.find(root_files, { stop = vim.env.HOME })
--   local root_dir = vim.fs.dirname(paths[1])
--
--   if root_dir == nil then
--     -- root directory was not found
--     return
--   end
--
--   vim.lsp.start({
--     name = "tsgo",
--     cmd = { "/Users/tin/private/typescript-go/built/local/tsgo", "--lsp", "-stdio" },
--     root_dir = root_dir,
--     -- init_options = { hostInfo = "neovim" }, -- not implemented yet
--   })
-- end
--
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "javascript", "javascriptreact", "javascript.jsx", "typescript", "typescriptreact", "typescript.tsx" },
--   desc = "Start tsgo LSP",
--   callback = start_tsgo,
-- })
