return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = { "windwp/nvim-ts-autotag" },
    opts = {
      auto_install = true,
      ensure_installed = {
        "lua",
        "vim",
        "go",
        "toml",
        "css",
        "tsx",
        "css",
        "html",
        "lua",
      },
      highlight = {
        enable = true,
        use_languagetree = true,
      },
      autotag = {
        enable = true,
        enable_rename = true,
        enable_close = true,
        enable_close_on_slash = true,
        filetypes = {
          "html",
          "javascript",
          "typescript",
          "javascriptreact",
          "typescriptreact",
          "svelte",
          "vue",
          "tsx",
          "jsx",
          "rescript",
          "css",
          "lua",
          "xml",
          "php",
          "markdown",
        },
      },
      indent = { enable = true },
    },
  },
}
